---
layout: default
title: Isaac  Portfolio
description: "Portfolio profesional de Isaac"
theme: jekyll-theme-cayman
---

# Hola, soy Isaac

Soy analista de datos. Me especializo en:

- Análisis de datos
- Automatización de procesos

## Proyectos Destacados

### [Proyecto 1](https://github.com/isaacbu710/Producci-n_de_aguacate_Mexico/blob/main/README.md)

### [Proyecto 2](https://github.com/isaacbu710/Proyecto_Analitico_con_Pruebas_AB_SQL_y_Visualizacion_de_Metricas)

### [Proyecto 3](https://github.com/isaacbu710/NOMBRE_PROYECTO3)
Breve descripción del proyecto y tecnologías utilizadas.

## Sobre mí

Soy un profesional apasionado por la tecnología y la data, con habilidades en comunicación, trabajo en equipo y resolución de problemas. Me gusta generar valor al negocio a través de soluciones efectivas y creativas.

## Contacto

- **Email:** hernandez_burgos@outlook.com 
- **LinkedIn:** [linkedin.com/in/isaacbuendia](www.linkedin.com/in/isaachernandez-dataanalyst)  
- **GitHub:** [github.com/isaacbu710](https://github.com/isaacbu710)
