---
layout: default
title: Isaac Buendía Portfolio
---

# Hola, soy Isaac Buendía

Soy desarrollador y analista de datos. Me especializo en:

- Desarrollo web
- Análisis de datos
- Automatización de procesos
- QA y pruebas de software

## Proyectos Destacados

### [Proyecto 1](https://github.com/isaacbu710/NOMBRE_PROYECTO1)
Breve descripción del proyecto y tecnologías utilizadas.

### [Proyecto 2](https://github.com/isaacbu710/NOMBRE_PROYECTO2)
Breve descripción del proyecto y tecnologías utilizadas.

### [Proyecto 3](https://github.com/isaacbu710/NOMBRE_PROYECTO3)
Breve descripción del proyecto y tecnologías utilizadas.

## Sobre mí

Soy un profesional apasionado por la tecnología y la data, con habilidades en comunicación, trabajo en equipo y resolución de problemas. Me gusta generar valor al negocio a través de soluciones efectivas y creativas.

## Contacto

- **Email:** isaac@example.com  
- **LinkedIn:** [linkedin.com/in/isaacbuendia](https://www.linkedin.com/in/isaacbuendia)  
- **GitHub:** [github.com/isaacbu710](https://github.com/isaacbu710)
